#Generated by thrift from line.thrift on http://altrepo.eu/git/line-protocol

__all__ = ['ttypes', 'constants', 'AccountSupervisorService', 'AgeCheckService', 'BuddyManagementService', 'BuddyService', 'ChannelApplicationProvidedService', 'ChannelService', 'MessageService', 'ShopService', 'SnsAdaptorService', 'TalkService', 'UniversalNotificationService']
